version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-devops
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    privileged: true
    user: root
    ports:
      - 8082:8080
      - 50001:50000
    container_name: jenkins-devops
    restart: unless-stopped
    environment:
      - "JAVA_OPTS=-Xms1024M -Xmx2048M"
    volumes:
      - jenkins_home_data:/var/jenkins_home      
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
    jenkins_home_data: